// Copyright (C) 2026 Lewandowskista
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using QAssistant.Models;

namespace QAssistant.Services
{
    /// <summary>
    /// Generates structured bug reports from a ProjectTask or a failed TestCase.
    /// </summary>
    public static class BugReportService
    {
        /// <summary>Generate a Markdown-formatted bug report from a task.</summary>
        public static string GenerateFromTask(ProjectTask task, string environment = "", string reporter = "")
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# Bug Report: {task.Title}");
            sb.AppendLine();
            sb.AppendLine("## Summary");
            sb.AppendLine($"> {task.Title}");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(task.IssueIdentifier))
            {
                sb.AppendLine("## Reference");
                sb.AppendLine($"- **Issue ID:** {task.IssueIdentifier}");
                if (!string.IsNullOrWhiteSpace(task.TicketUrl))
                    sb.AppendLine($"- **Ticket URL:** {task.TicketUrl}");
                sb.AppendLine();
            }

            sb.AppendLine("## Environment");
            sb.AppendLine($"- **Environment:** {(string.IsNullOrWhiteSpace(environment) ? "Not specified" : environment)}");
            sb.AppendLine($"- **Date Reported:** {DateTime.Now:yyyy-MM-dd HH:mm}");
            if (!string.IsNullOrWhiteSpace(reporter))
                sb.AppendLine($"- **Reporter:** {reporter}");
            if (!string.IsNullOrWhiteSpace(task.Assignee))
                sb.AppendLine($"- **Assigned To:** {task.Assignee}");
            sb.AppendLine();

            sb.AppendLine("## Priority & Severity");
            sb.AppendLine($"- **Priority:** {task.Priority}");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(task.Description))
            {
                sb.AppendLine("## Description");
                sb.AppendLine(task.Description);
                sb.AppendLine();
            }

            sb.AppendLine("## Steps to Reproduce");
            sb.AppendLine("1. ");
            sb.AppendLine("2. ");
            sb.AppendLine("3. ");
            sb.AppendLine();

            sb.AppendLine("## Expected Result");
            sb.AppendLine("> _Describe what should happen_");
            sb.AppendLine();

            sb.AppendLine("## Actual Result");
            sb.AppendLine("> _Describe what actually happens_");
            sb.AppendLine();

            if (task.AttachmentUrls.Count > 0)
            {
                sb.AppendLine("## Attachments");
                foreach (var url in task.AttachmentUrls)
                    sb.AppendLine($"- {url}");
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(task.Labels))
            {
                sb.AppendLine("## Labels");
                sb.AppendLine(task.Labels);
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine($"*Generated by QAssistant on {DateTime.Now:yyyy-MM-dd HH:mm}*");

            return sb.ToString();
        }

        /// <summary>Generate a Markdown-formatted bug report from a failed test case.</summary>
        public static string GenerateFromTestCase(TestCase tc, string testPlanName = "", string environment = "", string reporter = "")
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# Bug Report: {tc.Title}");
            sb.AppendLine();
            sb.AppendLine("## Summary");
            sb.AppendLine($"> {tc.Title}");
            sb.AppendLine();

            sb.AppendLine("## Reference");
            sb.AppendLine($"- **Test Case ID:** {tc.TestCaseId}");
            if (!string.IsNullOrWhiteSpace(testPlanName))
                sb.AppendLine($"- **Test Plan:** {testPlanName}");
            if (!string.IsNullOrWhiteSpace(tc.SourceIssueId))
                sb.AppendLine($"- **Source Issue:** {tc.SourceIssueId}");
            sb.AppendLine();

            sb.AppendLine("## Environment");
            sb.AppendLine($"- **Environment:** {(string.IsNullOrWhiteSpace(environment) ? "Not specified" : environment)}");
            sb.AppendLine($"- **Date Reported:** {DateTime.Now:yyyy-MM-dd HH:mm}");
            if (!string.IsNullOrWhiteSpace(reporter))
                sb.AppendLine($"- **Reporter:** {reporter}");
            sb.AppendLine();

            sb.AppendLine("## Priority & Severity");
            sb.AppendLine($"- **Priority:** {tc.Priority}");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(tc.PreConditions))
            {
                sb.AppendLine("## Pre-Conditions");
                sb.AppendLine(tc.PreConditions);
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(tc.TestSteps))
            {
                sb.AppendLine("## Steps to Reproduce");
                sb.AppendLine(tc.TestSteps);
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(tc.ExpectedResult))
            {
                sb.AppendLine("## Expected Result");
                sb.AppendLine(tc.ExpectedResult);
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(tc.ActualResult))
            {
                sb.AppendLine("## Actual Result");
                sb.AppendLine(tc.ActualResult);
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(tc.TestData))
            {
                sb.AppendLine("## Test Data");
                sb.AppendLine(tc.TestData);
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine($"*Generated by QAssistant on {DateTime.Now:yyyy-MM-dd HH:mm}*");

            return sb.ToString();
        }

        /// <summary>
        /// Generate a Markdown bug report from a failed test case, enriched with
        /// execution history and the latest AI analysis entry.
        /// </summary>
        public static string GenerateFromTestCase(
            TestCase tc,
            string testPlanName,
            string environment,
            string reporter,
            IEnumerable<TestExecution>? executions,
            string? aiAnalysis = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# Bug Report: {tc.Title}");
            sb.AppendLine();
            sb.AppendLine("## Summary");
            sb.AppendLine($"> {tc.Title}");
            sb.AppendLine();

            sb.AppendLine("## Reference");
            sb.AppendLine($"- **Test Case ID:** {tc.TestCaseId}");
            if (!string.IsNullOrWhiteSpace(testPlanName))
                sb.AppendLine($"- **Test Plan:** {testPlanName}");
            if (!string.IsNullOrWhiteSpace(tc.SourceIssueId))
                sb.AppendLine($"- **Source Issue:** {tc.SourceIssueId}");
            sb.AppendLine();

            sb.AppendLine("## Environment");
            sb.AppendLine($"- **Environment:** {(string.IsNullOrWhiteSpace(environment) ? "Not specified" : environment)}");
            sb.AppendLine($"- **Date Reported:** {DateTime.Now:yyyy-MM-dd HH:mm}");
            if (!string.IsNullOrWhiteSpace(reporter))
                sb.AppendLine($"- **Reporter:** {reporter}");
            sb.AppendLine();

            sb.AppendLine("## Priority & Severity");
            sb.AppendLine($"- **Priority:** {tc.Priority}");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(tc.PreConditions))
            {
                sb.AppendLine("## Pre-Conditions");
                sb.AppendLine(tc.PreConditions);
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(tc.TestSteps))
            {
                sb.AppendLine("## Steps to Reproduce");
                sb.AppendLine(tc.TestSteps);
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(tc.ExpectedResult))
            {
                sb.AppendLine("## Expected Result");
                sb.AppendLine(tc.ExpectedResult);
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(tc.ActualResult))
            {
                sb.AppendLine("## Actual Result");
                sb.AppendLine(tc.ActualResult);
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(tc.TestData))
            {
                sb.AppendLine("## Test Data");
                sb.AppendLine(tc.TestData);
                sb.AppendLine();
            }

            // Execution history
            var execList = executions?.OrderByDescending(e => e.ExecutedAt).Take(5).ToList();
            if (execList?.Count > 0)
            {
                sb.AppendLine("## Execution History");
                sb.AppendLine($"| Execution | Result | Date | Notes |");
                sb.AppendLine($"|-----------|--------|------|-------|");
                foreach (var ex in execList)
                    sb.AppendLine($"| {ex.ExecutionId} | {ex.Result} | {ex.ExecutedAt:yyyy-MM-dd HH:mm} | {ex.Notes.Replace("|", "\\|")} |");
                sb.AppendLine();
            }

            // AI analysis
            if (!string.IsNullOrWhiteSpace(aiAnalysis))
            {
                sb.AppendLine("## AI Analysis");
                sb.AppendLine(aiAnalysis);
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine($"*Generated by QAssistant on {DateTime.Now:yyyy-MM-dd HH:mm}*");

            return sb.ToString();
        }

        /// <summary>
        /// Generate a Markdown bug report from a task, enriched with AI analysis history.
        /// </summary>
        public static string GenerateFromTask(
            ProjectTask task,
            string environment,
            string reporter,
            string? aiAnalysis)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# Bug Report: {task.Title}");
            sb.AppendLine();
            sb.AppendLine("## Summary");
            sb.AppendLine($"> {task.Title}");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(task.IssueIdentifier))
            {
                sb.AppendLine("## Reference");
                sb.AppendLine($"- **Issue ID:** {task.IssueIdentifier}");
                if (!string.IsNullOrWhiteSpace(task.TicketUrl))
                    sb.AppendLine($"- **Ticket URL:** {task.TicketUrl}");
                sb.AppendLine();
            }

            sb.AppendLine("## Environment");
            sb.AppendLine($"- **Environment:** {(string.IsNullOrWhiteSpace(environment) ? "Not specified" : environment)}");
            sb.AppendLine($"- **Date Reported:** {DateTime.Now:yyyy-MM-dd HH:mm}");
            if (!string.IsNullOrWhiteSpace(reporter))
                sb.AppendLine($"- **Reporter:** {reporter}");
            if (!string.IsNullOrWhiteSpace(task.Assignee))
                sb.AppendLine($"- **Assigned To:** {task.Assignee}");
            sb.AppendLine();

            sb.AppendLine("## Priority & Severity");
            sb.AppendLine($"- **Priority:** {task.Priority}");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(task.Description))
            {
                sb.AppendLine("## Description");
                sb.AppendLine(task.Description);
                sb.AppendLine();
            }

            sb.AppendLine("## Steps to Reproduce");
            sb.AppendLine("1. ");
            sb.AppendLine("2. ");
            sb.AppendLine("3. ");
            sb.AppendLine();

            sb.AppendLine("## Expected Result");
            sb.AppendLine("> _Describe what should happen_");
            sb.AppendLine();

            sb.AppendLine("## Actual Result");
            sb.AppendLine("> _Describe what actually happens_");
            sb.AppendLine();

            if (task.AttachmentUrls.Count > 0)
            {
                sb.AppendLine("## Attachments");
                foreach (var url in task.AttachmentUrls)
                    sb.AppendLine($"- {url}");
                sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(task.Labels))
            {
                sb.AppendLine("## Labels");
                sb.AppendLine(task.Labels);
                sb.AppendLine();
            }

            // AI analysis from history
            if (!string.IsNullOrWhiteSpace(aiAnalysis))
            {
                sb.AppendLine("## AI Analysis");
                sb.AppendLine(aiAnalysis);
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine($"*Generated by QAssistant on {DateTime.Now:yyyy-MM-dd HH:mm}*");

            return sb.ToString();
        }
    }
}
